### ISSUE TITLE
Valid german IBAN is not considered valid 

### ISSUE THREAD

**Issue by s-gurevich** [baumerdev/ibantools-germany#17]
## Expected Behavior
A specific valid IBAN is recognized as valid by `isValidIBAN` function.

## Actual Behavior
A specific valid IBAN is NOT recognized as valid by `isValidIBAN` function.

## Steps to Reproduce the Problem

Given:
`import { isValidIBAN } from 'ibantools-germany';`

1. `isValidIBAN(electronicIban)` usually qualifies German IBANs correctly
2. A single specific IBAN is not recognized as valid, while https://www.iban-rechner.de/iban_validieren.html states, that it is valid
3. I cannot share the IBAN, because it's personal data, but maybe this helps:

> BIC: GENODED1SPW (Wuppertal)   
> 
> Bank: Sparda-Bank West
> 
> Methode 51, Variante Methode D, Konto XXX, BLZ 33060592, Prüfziffer 0 steht an Position 10, erwartete Prüfziffer: 0. Überblick über die Berechnung:  Nimm die Ziffern auf den Positionen 5 bis 9 - hier: XXX -,  multipliziere sie von rechts nach links mit den Gewichten 2,3,4,5,6,  addiere die Produkte, bilde den Rest der Division durch 7, ziehe das  Ergebnis von 7 ab,  und das Ergebnis modulo 7 ist die erwartete  Prüfziffer.

## Specifications

Tested with
"ibantools-germany": "1.2301.5"

**Comment by baumerdev** [comment]
Can you checkout branch fix_method_51d and see if this resolves your problem.
I hope I found the problem in this case, because the description of iban-rechner seems to hide the crucial part "Verbleibt kein Rest, ist die Prüfziffer 0."

**Comment by s-gurevich** [comment]
I checked out the project und ran the validation tests with the given IBAN. I can confirm that the validation failed on `main` but was successful on `fix_method_51d` branch.
Thank you so much for lightning fast support and fixing the issue!

**Comment by baumerdev** [comment]
Fix is now included in updated npm package version [1.2302.1](https://www.npmjs.com/package/ibantools-germany/v/1.2302.1)
