### ISSUE TITLE
Valid german IBAN is not considered valid: Methode D6, Variante 1

### ISSUE THREAD

**Issue by s-gurevich** [baumerdev/ibantools-germany#18]
## Expected Behavior
A specific valid IBAN is recognized as valid by `isValidIBAN` function.

## Actual Behavior
A specific valid IBAN is NOT recognized as valid by `isValidIBAN` function.

## Steps to Reproduce the Problem

Given:
`import { isValidIBAN } from 'ibantools-germany';`

1. `isValidIBAN(electronicIban)` usually qualifies German IBANs correctly
2. A single specific IBAN is not recognized as valid, while https://www.iban-rechner.de/iban_validieren.html states, that it is valid
3. I cannot share the IBAN, because it's personal data, but maybe this helps:

> BIC: NOLADE21WED (Wedel)   
> 
> Bank: Stadtsparkasse Wedel
> 
> Methode D6,  Variante 1, Konto XXX, BLZ 22151730, Prüfziffer 5 steht an  Position 10, erwartete Prüfziffer: 5. Überblick über die Berechnung:  Nimm die Ziffern auf den Positionen 1 bis 9 - hier: XXX -,  multipliziere sie von rechts nach links mit den Gewichten  2,3,4,5,6,7,8,9,10, addiere die Produkte, bilde den Rest der Division  durch 11,  und das Ergebnis modulo 11 ist die erwartete Prüfziffer.

## Specifications

Tested with
"ibantools-germany": "1.2302.1"

**Comment by baumerdev** [comment]
Can you please checkout branch `fix_method_d6` and test if the result is as expected.

**Comment by s-gurevich** [comment]
I can confirm, that the IBAN is accepted on `fix_method_d6` branch. Thank you very much!

**Comment by baumerdev** [comment]
Fixed in [v1.2302.2](https://www.npmjs.com/package/ibantools-germany/v/1.2302.2)
