### ISSUE TITLE
 Valid german IBAN is not considered valid: Methode 85

### ISSUE THREAD

**Issue by s-gurevich** [baumerdev/ibantools-germany#19]
## Expected Behavior
A specific valid IBAN is recognized as valid by `isValidIBAN` function.

## Actual Behavior
A specific valid IBAN is NOT recognized as valid by `isValidIBAN` function.

## Steps to Reproduce the Problem

Given:
`import { isValidIBAN } from 'ibantools-germany';`

1. `isValidIBAN(electronicIban)` usually qualifies German IBANs correctly
2. A single specific IBAN is not recognized as valid, while https://www.iban-rechner.de/iban_validieren.html states, that it is valid
3. I cannot share the IBAN, because it's personal data, but maybe this helps:

> Methode 85, Konto XXX, BLZ 40060560, Prüfziffer 0 steht an Position 10, erwartete Prüfziffer: 0. Überblick über die Berechnung: Nimm die Ziffern auf den Positionen 5 bis 9 - hier: XXX -, multipliziere sie von rechts nach links mit den Gewichten 2,3,4,5,6, addiere die Produkte, bilde den Rest der Division durch 7, ziehe das Ergebnis von 7 ab, und das Ergebnis modulo 7 ist die erwartete Prüfziffer.

## Specifications

Tested with
"ibantools-germany": "1.2302.2"

**Comment by baumerdev** [comment]
As usual 😉 Please have a look at branch `fix_method_85` and let me know if it works as expected.

**Comment by s-gurevich** [comment]
Tested :+1: 
Thank you so much again for amazingly fast support! :bouquet:

**Comment by baumerdev** [comment]
I try giving my best 😀

Fixed method is deployed in npm package [v1.2302.3](https://www.npmjs.com/package/ibantools-germany/v/1.2302.3)
