### ISSUE TITLE
Valid german IBAN is not considered valid: Methode 73, Variante 3

### ISSUE THREAD

**Issue by s-gurevich** [baumerdev/ibantools-germany#21]
## Expected Behavior
A specific valid IBAN is recognized as valid by `isValidIBAN` function.

## Actual Behavior
A specific valid IBAN is NOT recognized as valid by `isValidIBAN` function.

## Steps to Reproduce the Problem

Given:
`import { isValidIBAN } from 'ibantools-germany';`

1. `isValidIBAN(electronicIban)` usually qualifies German IBANs correctly
2. A single specific IBAN is not recognized as valid, while https://www.iban-rechner.de/iban_validieren.html states, that it is valid
3. I cannot share the IBAN, because it's personal data, but maybe this helps:

> Methode 73, Variante 3, Konto XXX, BLZ 50090500, Prüfziffer 0 steht an Position 10, erwartete Prüfziffer: 0. Überblick über die Berechnung: Nimm die Ziffern auf den Positionen 5 bis 9 - hier: XXX -, multipliziere sie von rechts nach links mit den Gewichten 2,1,2,1,2, addiere die Quersummen der Produkte, bilde den Rest der Division durch 7, ziehe das Ergebnis von 7 ab, und das Ergebnis modulo 7 ist die erwartete Prüfziffer.

## Specifications

Tested with
"ibantools-germany": "1.2401.0"

**Comment by baumerdev** [comment]
Can you checkout branch `fix_issue_21` if your bank account number is correctly flagged as valid.

**Comment by s-gurevich** [comment]
Yes, the fix works - thanks! :bouquet:

**Comment by baumerdev** [comment]
I published version `ibantools-germany@1.2401.1` that includes this fix.
